### ISSUE TITLE
no integration to add

### ISSUE THREAD

**Issue by myownkaos** [djtimca/hasatellitetracker#1]
i cant see the integration;
under 
conf>+integration>

**Comment by djtimca** [comment]
Need more information. 

Did you install through HACS or by copying the files?

Did you reboot after installing?

Try CTRL+F5 to force a refresh on the integration page after reboot and search again. 

Are there any errors in your logs?

**Comment by myownkaos** [comment]
hi install via hacs.
rebooted.
then F5 ed and it is all in integration and working.

thank you.
