### ISSUE TITLE
Sensor attributes exceed 16384 bytes

### ISSUE THREAD

**Issue by c3p0vsr2d2** [djtimca/hasatellitetracker#10]
Seems that the sensor size exceeds 16kB. 
Is there a workaroung to avoid this warning message?

`State attributes for sensor.home_overhead_satellites exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored`

**Comment by chuck99z28** [comment]
I wish I knew too.

**Comment by djtimca** [comment]
Reducing polling and radius to reduce the number of satellites. I have mine to polling: 30, radius: 20 and all working fine.
