### ISSUE TITLE
Too many attributes

### ISSUE THREAD

**Issue by matthew73210** [djtimca/hasatellitetracker#11]
The sensor is giving me 25k sats. I have polling at 600 to not saturate the API and a 90m radius. I doubt there are that many sats above me. Am I doing something wrong because when I click on atributes it crashes HA.

Cheers

**Comment by matthew73210** [comment]
Oh reducing the poll from 600 to 90 reduces the number of sats...

**Comment by djtimca** [comment]
Thanks - I don't plan to change anything for this.
