### ISSUE TITLE
SOURCE_TYPE_GPS a deprecated constant

### ISSUE THREAD

**Issue by dutch-erik** [djtimca/hasatellitetracker#12]
Logger: homeassistant.components.device_tracker.const
Source: helpers/deprecation.py:205
Integration: Device Tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 18:37:13 (1 occurrences)
Last logged: 18:37:13
SOURCE_TYPE_GPS was used from satellitetracker, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/djtimca/hasatellitetracker/issues

**Comment by jkfranks9** [comment]
Also TIME_SECONDS

**Comment by djtimca** [comment]
Release 0.0.9 updates these deprecated constants.
